### ISSUE TITLE
Add notes on proper usage

### ISSUE THREAD

**Issue by majestrate** [tailot/i2phosts#1]
On IRC2P just now,

    <@zzz> can somebody with a github acct open a bug on that hosts.txt scraper guy? He's running it every 3 minutes (!) and not using etag, so he's pulling the whole thing, 100KB, every 3 minutes
    ...
    <@zzz> there's no reason to run it more than once a day, and he's gotta use etag and merge.

Can we add a note to the readmes about not spamming this updater script?

**Comment by tailot** [comment]
Ok, sorry!!! Now run once a day.
Added a Warning to the readme.
